classdef ImagingReceiverTest < matlab.unittest.TestCase
    %IMAGINGRECEIVERTEST Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
    end
    
    methods(Test)
        function testConstructorNoArgument(~)
            ImagingReceiver();
        end % function testConstructorNoArgument
        
        function testConstructorDefaultPixelTemplate(tc)
            r_aperture = rand()/rand();
            
            [lenspoint, lens_to_array_distance, ...
                zenith_angle, azimuth, tilt, ...
                element_width, element_height, nrows, ncols, ...
                ~] = ...
                CameraArrayTest.genCameraArrayParameters();
            
            obj = ImagingReceiver(r_aperture, ...
                lenspoint, lens_to_array_distance, ...
                zenith_angle, azimuth, tilt, ...
                element_width, element_height, nrows, ncols);
            
            pixel_template_expected = ...
                CameraArrayTest.defaultPixelTemplate( ...
                element_width, element_height);
            
            ImagingReceiverTest.verifyProperties(tc, obj, ...
                r_aperture, lenspoint, lens_to_array_distance, ...
                zenith_angle, azimuth, tilt, ...
                element_width, element_height, nrows, ncols, ...
                pixel_template_expected);
        end % function testConstructorDefaultPixelTemplate
    end % methods(Test)
    
    methods(Static)
        function verifyProperties(tc, obj, ...
                r_aperture, lenspoint, lens_to_array_distance, ...
                zenith_angle, azimuth, tilt, ...
                element_width, element_height, nrows, ncols, ...
                pixel_template)
            
            tc.verifyEqual(obj.r_aperture, r_aperture);
            
            CameraArrayTest.verifyProperties(tc, obj, ...
                lenspoint, lens_to_array_distance, ...
                zenith_angle, azimuth, tilt, ...
                element_width, element_height, nrows, ncols, ...
                pixel_template);
        end % function verifyProperties
    end % methods(Static)
end

